name: example-nessus

services:
  nessus:
    image: tenable/nessus:latest-ubuntu
    container_name: nessus
    ports:
      - "8834:8834"
    env_file:
      - .env
    environment:
      USERNAME: "admin"
      PASSWORD: "password"
      NAME: "Vergissberlin Nessus"
      AUTO_UPDATE: "all"
    volumes:
      - ./data/security-center:/opt/nessus/var
  